# Se docs for hvordan definere rules:
# - https://docs.nais.io/observability/alerting/
# - https://docs.nais.io/observability/alerting/reference/prometheusrule/#prometheusrule
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: veilarbpersonflate-alerts
  namespace: poao
  labels:
    team: poao
spec:
  groups:
    - name: Deployment
      rules:
        - alert: applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="veilarbpersonflate"} == 0
          for: 12m
          annotations:
            consequence: "'{{ $labels.deployment }}' er utilgjengelig"
            action: "`kubectl describe pod -l app={{ $labels.deployment }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l app={{ $labels.deployment }} -n {{ $labels.namespace }}` for logger"
            summary: |-
              '{{ $labels.deployment }}' er utilgjengelig. Dette burde fikses asap!

              Dette kan ha skjedd som følge av endringer i NAIS config eller at det er noe galt i plattformen.
          labels:
            namespace: poao
            severity: critical
        - alert: "Applikasjon starter ikke"
          expr: kube_deployment_status_replicas_unavailable{deployment="veilarbpersonflate"} > 0
          for: 5m
          annotations:
            consequence: Minst én pod er utilgjengelig og nye kodeendringer har sannsynligvis ikke blitt produksjonssatt.
            action: "`kubectl describe pod -l app={{ $labels.deployment }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l app={{ $labels.deployment }} -n {{ $labels.namespace }}` for logger"
            summary: |
              '{{ $labels.deployment }}' kunne ikke startes og har sannsynligvis havnet i CrashLoopBackoff under deployment.

              Sjekk loggene for å finne ut hva som er galt.
          labels:
            namespace: poao
            severity: critical