apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbpersonflatefs
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.03.04_10.27-769e37315ec1
  port: 8080
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://veilarbpersonflate.intern.nav.no/veilarbpersonflatefs
  gcp:
    buckets:
      - name: veilarbpersonflatefs-prod
        cascadingDelete: false
  env:
    - name: JSON_CONFIG
      value: >
        {
          "contextPath": "/veilarbpersonflatefs",
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "veilarbpersonflatefs-prod"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          }
        }
