apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbpersonflatefs
  namespace: default
  cluster:
    - prod-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbpersonflatefs/veilarbpersonflatefs:{{version}}
  port: 8080
  liveness:
    initialDelay: 20
      path: veilarbpersonflatefs/internal/isAlive
  readiness:
    path: veilarbpersonflatefs/internal/selftest
    initialDelay: 20
  prometheus:
    enabled: true
    path: veilarbpersonflatefs/internal/metrics
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://veilarbpersonflatefs.nais.adeo.no
    - https://app.adeo.no/veilarbpersonflatefs
  vault:
    enabled: true
  env:
    - ISSO_JWKS_URL
    - ISSO_HOST_URL
    - ISSO_ISSUER_URL
    - ISSO_ISALIVE_URL
    - VEILARBLOGIN_REDIRECT_URL_URL
    - VEILARBLOGIN_REDIRECT_URL_DESCRIPTION
    - OIDC_REDIRECT_URL