apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbpersonflate
  namespace: poao
  labels:
    team: poao
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.05.18_10.19-08a4135c0657
  port: 8080
  ingresses:
    - https://veilarbpersonflatefs.dev.intern.nav.no # TODO: rename til https://veilarbpersonflate.dev.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    buckets:
      - name: poao-veilarbpersonflate-dev
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: poao-unleash

  env:
    - name: JSON_CONFIG
      value: >
        {
          "enableSecureLogs": true,
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "gcs": {
            "bucketName": "poao-veilarbpersonflate-dev"
          },
          "redirects": [
            {
              "fromPath": "/internarbeidsflatedecorator/*",
              "toUrl": "https://internarbeidsflatedecorator-q1.dev.intern.nav.no",
              "preserveFromPath": true
            }
          ],
          "proxies": [
            {
              "fromPath": "/frontendlogger",
              "toUrl": "https://frontendlogger.dev-fss-pub.nais.io",
              "preserveFromPath": true
            },
            {
              "fromPath": "/veilarbperson",
              "toUrl": "https://veilarbperson.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbperson",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarboppfolging",
              "toUrl": "https://veilarboppfolging.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarboppfolging",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbdialog",
              "toUrl": "https://veilarbdialog.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbdialog",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbaktivitet",
              "toUrl": "https://veilarbaktivitet.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbaktivitet",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbportefolje",
              "toUrl": "https://veilarbportefolje.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbportefolje",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbpersonflatefs",
              "toUrl": "http://poao-unleash.poao.svc.cluster.local",
              "preserveFromPath": false
            },
            {
              "fromPath": "/modiacontextholder",
              "toUrl": "https://modiacontextholder-q1.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "modiacontextholder-q1",
                "namespace": "personoversikt",
                "cluster": "dev-fss"
              }
            }
          ]
        }