apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbpersonflate
  namespace: poao
  labels:
    team: poao
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.08.01_11.00-f813dcd15fd5
  port: 8080
  ingresses:
    - https://veilarbpersonflate.dev.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    buckets:
      - name: poao-veilarbpersonflate-dev
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: poao-unleash
      external:
        - host: veilarbdialog.dev-fss-pub.nais.io
        - host: veilarbaktivitet.dev-fss-pub.nais.io
        - host: veilarblest.dev-fss-pub.nais.io
  env:
    - name: JSON_CONFIG
      value: >
        {
          "enableSecureLogs": true,
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "gcs": {
            "bucketName": "poao-veilarbpersonflate-dev"
          },
          "header": {
            "csp": {
              "connectSrc": ["'self'", "wss:", "*.nav.no", "*.adeo.no", "cdn.sanity.io"]
            }
          },
          "redirects": [
            {
              "fromPath": "/internarbeidsflatedecorator/*",
              "toUrl": "https://internarbeidsflatedecorator-q1.dev.intern.nav.no",
              "preserveFromPath": true
            },
            {
              "fromPath": "/registrer-tilretteleggingsbehov/*",
              "toUrl": "https://registrer-tilretteleggingsbehov.dev.intern.nav.no",
              "preserveFromPath": true
            },
            {
              "fromPath": "/veilarbportefoljeflatefs/*",
              "toUrl": "https://veilarbportefoljeflate.dev.intern.nav.no",
              "preserveFromPath": false
            }
          ],
          "proxies": [
            {
              "fromPath": "/veilarbmalverk",
              "toUrl": "https://veilarbmalverk.dev-fss-pub.nais.io",
              "preserveFromPath": true
            },
            {
              "fromPath": "/veilarbperson",
              "toUrl": "https://veilarbperson.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbperson",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarboppfolging",
              "toUrl": "https://veilarboppfolging.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarboppfolging",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbdialog",
              "toUrl": "https://veilarbdialog.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbdialog",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbaktivitet",
              "toUrl": "https://veilarbaktivitet.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbaktivitet",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarblest",
              "toUrl": "https://veilarblest.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarblest",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbportefolje",
              "toUrl": "https://veilarbportefolje.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbportefolje",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbpersonflatefs",
              "toUrl": "http://poao-unleash.poao.svc.cluster.local",
              "preserveFromPath": false,
               "toApp": {
                "name": "poao-unleash",
                "namespace": "poao",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/modiacontextholder",
              "toUrl": "https://modiacontextholder-q1.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "modiacontextholder-q1",
                "namespace": "personoversikt",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbveileder",
              "toUrl": "https://veilarbveileder.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbveileder",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbvedtaksstotte",
              "toUrl": "https://veilarbvedtaksstotte.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbvedtaksstotte",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/finn-kandidat-api",
              "toUrl": "https://finn-kandidat-api.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "finn-kandidat-api",
                "namespace": "arbeidsgiver",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/mulighetsrommet-api",
              "toUrl": "https://mulighetsrommet-api.dev.intern.nav.no",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-api",
                "namespace": "team-mulighetsrommet",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/veilarboppgave",
              "toUrl": "https://veilarboppgave.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarboppgave",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            }
          ]
        }