apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbpersonflate
  namespace: poao
  labels:
    team: poao
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.06.21_07.33-5244a7b7ae64
  port: 8080
  ingresses:
    - https://veilarbpersonflate.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    buckets:
      - name: poao-veilarbpersonflate-prod
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: poao-unleash

  env:
    - name: JSON_CONFIG
      value: >
        {
          "enableSecureLogs": true,
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "gcs": {
            "bucketName": "poao-veilarbpersonflate-prod"
          },
          "header": {
            "csp": {
              "connectSrc": ["'self'", "wss:", "*.nav.no", "*.adeo.no"]
            }
          },
          "redirects": [
            {
              "fromPath": "/internarbeidsflatedecorator/*",
              "toUrl": "https://internarbeidsflatedecorator.intern.nav.no",
              "preserveFromPath": true
            },
            {
              "fromPath": "/registrer-tilretteleggingsbehov/*",
              "toUrl": "https://registrer-tilretteleggingsbehov.intern.nav.no",
              "preserveFromPath": true
            },
            {
              "fromPath": "/veilarbportefoljeflatefs/*",
              "toUrl": "https://veilarbportefoljeflatefs.intern.nav.no",
              "preserveFromPath": false
            }
          ],
          "proxies": [
            {
              "fromPath": "/frontendlogger",
              "toUrl": "https://frontendlogger.prod-fss-pub.nais.io",
              "preserveFromPath": true
            },
            {
              "fromPath": "/veilarbperson",
              "toUrl": "https://veilarbperson.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbperson",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarboppfolging",
              "toUrl": "https://veilarboppfolging.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarboppfolging",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbdialog",
              "toUrl": "https://veilarbdialog.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbdialog",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbportefolje",
              "toUrl": "https://veilarbportefolje.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbportefolje",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbaktivitet",
              "toUrl": "https://veilarbaktivitet.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbaktivitet",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarblest",
              "toUrl": "https://veilarblest.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarblest",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbpersonflatefs",
              "toUrl": "http://pto-unleash.pto.svc.nais.local",
              "preserveFromPath": false
            },
            {
              "fromPath": "/modiacontextholder",
              "toUrl": "https://modiacontextholder.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "modiacontextholder",
                "namespace": "personoversikt",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbveileder",
              "toUrl": "https://veilarbveileder.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbveileder",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbvedtaksstotte",
              "toUrl": "https://veilarbvedtaksstotte.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbvedtaksstotte",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/finn-kandidat-api",
              "toUrl": "https://finn-kandidat-api.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "finn-kandidat-api",
                "namespace": "arbeidsgiver",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/mulighetsrommet-api",
              "toUrl": "https://mulighetsrommet-api.intern.nav.no",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-veileder-flate",
                "namespace": "team-mulighetsrommet",
                "cluster": "prod-gcp"
              }
            },
            {
              "fromPath": "/veilarboppgave",
              "toUrl": "https://veilarboppgave.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarboppgave",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            }
          ]
        }